name: tempworkflow

on: push

jobs:
  doeverything:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: aws config
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: zipproject
        run: |
          zip -r website.zip *

      - name: copytos3
        run: |
          aws s3 cp website.zip s3://someabeylarkey/website.zip --region us-east-1

      - name: createapp
        run: |
          aws elasticbeanstalk create-application-version --application-name myapp --version-label myapp-v5 --region us-east-1 --source-bundle S3Bucket=someabeylarkey,S3Key=website.zip --auto-create-application

      - name: installeb
        run: |
          pip install awsebcli --upgrade --user

      - name: deployeb
        run: |
          eb init -i myapp -k assignment-02-kp -p Node.js --region us-east-1
          eb deploy Myapp-env-1 --version myapp-v5


